[package]
name = "rpc_call"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonrpsee = { version = "0.21.0", features = ["client", "macros"]}
serde = "1.0.193"