[package]
name = "rpc_call_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.34"
syn = "2.0.44"
jsonrpsee = { version = "0.21.0", features = ["client", "macros"]}
serde = "1.0.193"
rpc_call = { path = "../rpc_call" }